const orders = [
  {
    order_id: 1,
    customer_name: "John Doe",
    address: "1234 Main St",
    complaints: ["Complaint 1", "Complaint 2"],
    cart: [
      {
        product_id: 1,
        product_name: "Product 1",
        quantity: 2,
        price: 10.99,
      },
      {
        product_id: 2,
        product_name: "Product 2",
        quantity: 1,
        price: 5.99,
      },
    ],
    refunded_items: [
      {
        product_id: 1,
        product_name: "Product 1",
        quantity: 1,
        price: 10.99,
      },
    ],
    total: 87.97,
    order_status: "Delivered",
    tax: 2.97,
    discount: 0.0,
    time: "2021-09-01T12:00:00Z",
    order_type: "Delivery",
    payment_method: "Cash",
  },
  {
    order_id: 2,
    customer_name: "Jane Smith",
    address: "5678 Market St",
    complaints: [],
    cart: [
      {
        product_id: 3,
        product_name: "Product 3",
        quantity: 1,
        price: 15.99,
      },
    ],
    refunded_items: [],
    total: 15.99,
    order_status: "Pending",
    tax: 1.60,
    discount: 1.0,
    time: "2021-09-01T14:00:00Z",
    order_type: "Pickup",
    payment_method: "PayPal",
  },
  {
    order_id: 3,
    customer_name: "Bob Johnson",
    address: "9101 Second St",
    complaints: ["Late delivery"],
    cart: [
      {
        product_id: 4,
        product_name: "Product 4",
        quantity: 3,
        price: 7.99,
      },
      {
        product_id: 5,
        product_name: "Product 5",
        quantity: 2,
        price: 6.49,
      },
    ],
    refunded_items: [],
    total: 36.94,
    order_status: "Delivered",
    tax: 3.69,
    discount: 2.0,
    time: "2021-09-01T16:00:00Z",
    order_type: "Delivery",
    payment_method: "Debit Card",
  },
  {
    order_id: 4,
    customer_name: "Alice Davis",
    address: "1213 Third St",
    complaints: ["Wrong item received"],
    cart: [
      {
        product_id: 6,
        product_name: "Product 6",
        quantity: 1,
        price: 20.00,
      },
    ],
    refunded_items: [
      {
        product_id: 6,
        product_name: "Product 6",
        quantity: 1,
        price: 20.00,
      },
    ],
    total: 20.00,
    order_status: "Refunded",
    tax: 2.00,
    discount: 0.0,
    time: "2021-09-04T18:00:00Z",
    order_type: "Delivery",
    payment_method: "Credit Card",
  },
  {
    order_id: 5,
    customer_name: "Charlie Brown",
    address: "1415 Fourth St",
    complaints: [],
    cart: [
      {
        product_id: 7,
        product_name: "Product 7",
        quantity: 2,
        price: 12.99,
      },
      {
        product_id: 8,
        product_name: "Product 8",
        quantity: 1,
        price: 8.99,
      },
    ],
    refunded_items: [],
    total: 34.97,
    order_status: "Delivered",
    tax: 3.50,
    discount: 1.5,
    time: "2021-09-05T20:00:00Z",
    order_type: "Pickup",
    payment_method: "Cash",
  },
  {
    order_id: 6,
    customer_name: "Diana Prince",
    address: "1617 Fifth St",
    complaints: ["Damaged item"],
    cart: [
      {
        product_id: 9,
        product_name: "Product 9",
        quantity: 1,
        price: 25.00,
      },
    ],
    refunded_items: [
      {
        product_id: 9,
        product_name: "Product 9",
        quantity: 1,
        price: 25.00,
      },
    ],
    total: 25.00,
    order_status: "Refunded",
    tax: 2.50,
    discount: 0.0,
    time: "2021-09-06T22:00:00Z",
    order_type: "Delivery",
    payment_method: "Credit Card",
  },
  {
    order_id: 7,
    customer_name: "Eve Harris",
    address: "1819 Sixth St",
    complaints: [],
    cart: [
      {
        product_id: 10,
        product_name: "Product 10",
        quantity: 2,
        price: 10.00,
      },
    ],
    refunded_items: [],
    total: 20.00,
    order_status: "Delivered",
    tax: 2.00,
    discount: 0.0,
    time: "2021-09-07T10:00:00Z",
    order_type: "Pickup",
    payment_method: "PayPal",
  },
  {
    order_id: 8,
    customer_name: "Frank Wright",
    address: "2021 Seventh St",
    complaints: ["Missing item"],
    cart: [
      {
        product_id: 11,
        product_name: "Product 11",
        quantity: 1,
        price: 30.00,
      },
      {
        product_id: 12,
        product_name: "Product 12",
        quantity: 1,
        price: 15.00,
      },
    ],
    refunded_items: [],
    total: 45.00,
    order_status: "Pending",
    tax: 4.50,
    discount: 0.0,
    time: "2021-09-08T12:00:00Z",
    order_type: "Delivery",
    payment_method: "Debit Card",
  },
  {
    order_id: 9,
    customer_name: "Grace Lee",
    address: "2223 Eighth St",
    complaints: [],
    cart: [
      {
        product_id: 13,
        product_name: "Product 13",
        quantity: 1,
        price: 40.00,
      },
    ],
    refunded_items: [],
    total: 40.00,
    order_status: "Delivered",
    tax: 4.00,
    discount: 0.0,
    time: "2021-09-09T14:00:00Z",
    order_type: "Pickup",
    payment_method: "Credit Card",
  },
  {
    order_id: 10,
    customer_name: "Hank Wilson",
    address: "2425 Ninth St",
    complaints: ["Late delivery", "Damaged item"],
    cart: [
      {
        product_id: 14,
        product_name: "Product 14",
        quantity: 2,
        price: 22.00,
      },
    ],
    refunded_items: [
      {
        product_id: 14,
        product_name: "Product 14",
        quantity: 1,
        price: 22.00,
      },
    ],
    total: 44.00,
    order_status: "Refunded",
    tax: 4.40,
    discount: 0.0,
    time: "2021-09-10T16:00:00Z",
    order_type: "Delivery",
    payment_method: "Cash",
  },
  {
    order_id: 11,
    customer_name: "Ivy Martinez",
    address: "2627 Tenth St",
    complaints: ["Wrong item received"],
    cart: [
      {
        product_id: 15,
        product_name: "Product 15",
        quantity: 1,
        price: 18.00,
      },
    ],
    refunded_items: [
      {
        product_id: 15,
        product_name: "Product 15",
        quantity: 1,
        price: 18.00,
      },
    ],
    total: 18.00,
    order_status: "Refunded",
    tax: 1.80,
    discount: 0.0,
    time: "2021-09-11T18:00:00Z",
    order_type: "Pickup",
    payment_method: "Credit Card",
  },
  {
    order_id: 12,
    customer_name: "Jack Brown",
    address: "2829 Eleventh St",
    complaints: [],
    cart: [
      {
        product_id: 16,
        product_name: "Product 16",
        quantity: 3,
        price: 9.00,
      },
    ],
    refunded_items: [],
    total: 27.00,
    order_status: "Delivered",
    tax: 2.70,
    discount: 1.0,
    time: "2021-09-01T20:00:00Z",
    order_type: "Delivery",
    payment_method: "Credit Card",
  },
  {
    order_id: 13,
    customer_name: "Karen White",
    address: "3031 Twelfth St",
    complaints: ["Damaged item"],
    cart: [
      {
        product_id: 1,
        product_name: "Product 1",
        quantity: 1,
        price: 50.00,
      },
    ],
    refunded_items: [
      {
        product_id: 1,
        product_name: "Product 1",
        quantity: 1,
        price: 50.00,
      },
    ],
    total: 50.00,
    order_status: "Refunded",
    tax: 5.00,
    discount: 0.0,
    time: "2021-09-13T22:00:00Z",
    order_type: "Pickup",
    payment_method: "Debit Card",
  },
  {
    order_id: 14,
    customer_name: "Liam Johnson",
    address: "3233 Thirteenth St",
    complaints: ["Late delivery"],
    cart: [
      {
        product_id: 1,
        product_name: "Product 1",
        quantity: 2,
        price: 12.00,
      },
    ],
    refunded_items: [],
    total: 24.00,
    order_status: "Delivered",
    tax: 2.40,
    discount: 0.0,
    time: "2021-09-14T10:00:00Z",
    order_type: "Delivery",
    payment_method: "Credit Card",
  },
  {
    order_id: 15,
    customer_name: "Mia Williams",
    address: "3435 Fourteenth St",
    complaints: ["Missing item"],
    cart: [
      {
        product_id: 1,
        product_name: "Product 1",
        quantity: 1,
        price: 35.00,
      },
    ],
    refunded_items: [],
    total: 35.00,
    order_status: "Pending",
    tax: 3.50,
    discount: 0.0,
    time: "2021-09-15T12:00:00Z",
    order_type: "Pickup",
    payment_method: "Cash",
  },
  {
    order_id: 16,
    customer_name: "Nina Clark",
    address: "3637 Fifteenth St",
    complaints: [],
    cart: [
      {
        product_id: 20,
        product_name: "Product 20",
        quantity: 1,
        price: 60.00,
      },
    ],
    refunded_items: [],
    total: 60.00,
    order_status: "Delivered",
    tax: 6.00,
    discount: 0.0,
    time: "2021-09-16T14:00:00Z",
    order_type: "Delivery",
    payment_method: "PayPal",
  },
  {
    order_id: 17,
    customer_name: "Oliver Davis",
    address: "3839 Sixteenth St",
    complaints: ["Wrong item received"],
    cart: [
      {
        product_id: 21,
        product_name: "Product 21",
        quantity: 2,
        price: 11.00,
      },
    ],
    refunded_items: [
      {
        product_id: 21,
        product_name: "Product 21",
        quantity: 1,
        price: 11.00,
      },
    ],
    total: 22.00,
    order_status: "Refunded",
    tax: 2.20,
    discount: 0.0,
    time: "2021-09-17T16:00:00Z",
    order_type: "Pickup",
    payment_method: "Credit Card",
  },
  {
    order_id: 18,
    customer_name: "Pam Green",
    address: "4041 Seventeenth St",
    complaints: ["Late delivery", "Damaged item"],
    cart: [
      {
        product_id: 22,
        product_name: "Product 22",
        quantity: 1,
        price: 55.00,
      },
    ],
    refunded_items: [
      {
        product_id: 22,
        product_name: "Product 22",
        quantity: 1,
        price: 55.00,
      },
    ],
    total: 55.00,
    order_status: "Refunded",
    tax: 5.50,
    discount: 0.0,
    time: "2021-09-18T18:00:00Z",
    order_type: "Delivery",
    payment_method: "Debit Card",
  },
  {
    order_id: 19,
    customer_name: "Quincy Adams",
    address: "4243 Eighteenth St",
    complaints: [],
    cart: [
      {
        product_id: 23,
        product_name: "Product 23",
        quantity: 3,
        price: 8.00,
      },
    ],
    refunded_items: [],
    total: 24.00,
    order_status: "Delivered",
    tax: 2.40,
    discount: 0.0,
    time: "2021-09-19T20:00:00Z",
    order_type: "Pickup",
    payment_method: "Cash",
  },
  {
    order_id: 20,
    customer_name: "Rachel Baker",
    address: "4445 Nineteenth St",
    complaints: ["Missing item"],
    cart: [
      {
        product_id: 24,
        product_name: "Product 24",
        quantity: 1,
        price: 70.00,
      },
    ],
    refunded_items: [],
    total: 70.00,
    order_status: "Pending",
    tax: 7.00,
    discount: 0.0,
    time: "2021-09-20T10:00:00Z",
    order_type: "Delivery",
    payment_method: "Credit Card",
  },
];

export default orders;