const data = [
    {
        id: 1,
        branch_name: "Branch 1",
        manager_ids: [1, 2],
        address: "123 Main St",
        contact: "123-456-7890",
        day_number: 1,
        opening_time: "08:00",
        closing_time: "18:00",
        shift_status: "Open",
        branch_city: "City 1",
        branch_sales: 100000,
        branch_cash_on_hand: 50000,
        shop_name: "Shop 1",
    },
    {
        id: 2,
        branch_name: "Branch 2",
        manager_ids: [3, 4],
        address: "456 Elm St",
        contact: "123-456-7890",
        day_number: 2,
        opening_time: "08:00",
        closing_time: "18:00",
        shift_status: "Open",
        branch_city: "City 2",
        branch_sales: 100000,
        branch_cash_on_hand: 50000,
        shop_name: "Shop 1",
    },
    {
        id: 3,
        branch_name: "Branch 3",
        manager_ids: [5, 6],
        address: "789 Oak St",
        contact: "123-456-7890",
        day_number: 3,
        opening_time: "08:00",
        closing_time: "18:00",
        shift_status: "Open",
        branch_city: "City 3",
        branch_sales: 100000,
        branch_cash_on_hand: 50000,
        shop_name: "Shop 1",
    }
];
    
export default data;